### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Shazgul** [FelixSchuSi/better-kickbase#1]
Hey, just an Question, how to use this? Is there any instruction?

**Comment by FelixSchuSi** [comment]
Hey, thanks for checking out my project, this extention is currently under development.
The goal is to improve the overall usability of play.kickbase.com.
When the extension is in a usable state I will publish it to the chrome and firefox extension store.

**Comment by FelixSchuSi** [comment]
Hey @Shazgul, the extension is now available on the [Mozilla Addon Store](https://addons.mozilla.org/de/firefox/addon/better-kickbase/). 
The Chrome Store is currently reviewing the extension, until then you need to install the extension manually using the [`better-kb.zip`](https://github.com/FelixSchuSi/better-kickbase/releases) file from the releases tab.

**Comment by FelixSchuSi** [comment]
Now also on [chrome web store](https://chrome.google.com/webstore/detail/better-kickbase/jdkehjokegcepbmbmcbaojnpkmnolgkg)
