### ISSUE TITLE
CSV Download button not showing up

### ISSUE THREAD

**Issue by drdentz** [FelixSchuSi/better-kickbase#3]
Where is the download button supposed to show up?
I can't see it? Do you know if there are negative effects if there are adblocker Plugins running?

**Comment by FelixSchuSi** [comment]
The button is supposed to show up on the selling page (`/transfermarkt/verkaufen`) at the buttom right.
Make sure that you have enabled csv export in the settings of the extension (it is enabled by default).
Adblockers should have no effect on the extension.
![csvexport](https://user-images.githubusercontent.com/47390169/129341797-5b43996d-e7c3-4c1f-8d6c-ad4e704c1122.png)
![csv-setting](https://user-images.githubusercontent.com/47390169/129341800-18509f28-8459-4798-b51d-427c47fed00c.png)

Let me know if you managed to get the extension working!

**Comment by drdentz** [comment]
Ah gefunden. Ich hab sie im Reiter Kader erwartet. Wunderbar.
Wäre es noch möglich die Position der Spieler wegzuschreiben?

**Comment by FelixSchuSi** [comment]
Gute Idee!
Die Spalten, die beim export enthalten sind könnten in den Einstellungen an- und abwählbar gemacht werden👍🏽
